### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: 'experiments/baroque_dining_room/checkpoints/step_000500'

### ISSUE THREAD

**Issue by StevenLzq** [DanaCohen95/Set-the-Scene#6]
a problem occured when we run  python -m scripts.train_scene_nerf --config_path demo_configs/garage.yaml
23% training step 3500/15000 [19:53<49:05,  3.90it/s]Traceback (most recent call last):
  File "/home/sda/cv3d/anaconda3/envs/sts/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sda/cv3d/anaconda3/envs/sts/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sda/cv3d/lzq/Set-the-Scene/scripts/train_scene_nerf.py", line 18, in <module>
    main()
  File "/home/sda/cv3d/anaconda3/envs/sts/lib/python3.8/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/sda/cv3d/lzq/Set-the-Scene/scripts/train_scene_nerf.py", line 14, in main
    scene_trainer.train()
  File "/home/sda/cv3d/lzq/Set-the-Scene/src/latent_nerf/training/scene_trainer.py", line 230, in train
    self.save_checkpoint(full=True)
  File "/home/sda/cv3d/lzq/Set-the-Scene/src/latent_nerf/training/scene_trainer.py", line 460, in save_checkpoint
    old_ckpt.unlink()
  File "/home/sda/cv3d/anaconda3/envs/sts/lib/python3.8/pathlib.py", line 1325, in unlink
    self._accessor.unlink(self)
IsADirectoryError: [Errno 21] Is a directory: 'experiments/baroque_dining_room/checkpoints/step_000500'

**Comment by DanaCohen95** [comment]
you are right,  it should be switched to    
```'
shutil.rmtree(old_ckpt)
```
I've updated the code.
